services:
  fastapi:
    container_name: fastapi
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - type: volume
        source: fastapi-files
        target: /usr/src/app/files
  nginx:
    container_name: nginx
    build: nginx/
    ports:
      - 80:80
    restart: always
    volumes:
      - type: volume
        source: fastapi-files
        target: /var/www/fastapi/files

  mongo:
    container_name: mango
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hard
    volumes:
      - type: volume
        source: mangodata
        target: /data/db

  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=hard
      - POSTGRES_USER=main
      - POSTGRES_DB=fastapi
    volumes:
      - type: volume
        source: postgresdata
        target: /var/lib/postgresql/data

volumes:
  fastapi-files:
    external: true
  mangodata:
    external: true
  postgresdata:
    external: true
