"""Added notification is canceled

Revision ID: 15692b194ff3
Revises: dcc32d86f9a3
Create Date: 2024-09-08 20:30:59.224759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15692b194ff3'
down_revision: Union[str, None] = 'dcc32d86f9a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('is_canceled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'is_canceled')
    # ### end Alembic commands ###
