"""Added notification created_at field

Revision ID: 514174e44a8d
Revises: 6b5683565e7b
Create Date: 2024-09-07 10:16:24.070101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '514174e44a8d'
down_revision: Union[str, None] = '6b5683565e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('created_at', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'created_at')
    # ### end Alembic commands ###
