"""Notification column name changed

Revision ID: 8bfeb67e4014
Revises: 45422f2df3c4
Create Date: 2024-11-16 13:37:49.770259

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8bfeb67e4014"
down_revision: Union[str, None] = "45422f2df3c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notifications", sa.Column("receiver_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint(
        "notifications_reciver_id_fkey", "notifications", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "notifications", "users", ["receiver_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("notifications", "reciver_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notifications",
        sa.Column("reciver_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "notifications", type_="foreignkey")
    op.create_foreign_key(
        "notifications_reciver_id_fkey",
        "notifications",
        "users",
        ["reciver_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "notifications",
        "notification_type",
        existing_type=postgresql.ENUM(
            "FRIEND_REQUEST",
            "FRIEND_REQUEST_ACCEPTED",
            "FRIEND_REQUEST_REJECTED",
            "FRIEND_REQUEST_CANCELED",
            "BLOCK_FRIEND",
            "UNBLOCK_FRIEND",
            "UNFRIEND",
            name="notificationtype",
        ),
        type_=postgresql.ENUM(
            "FRIEND_REQUEST",
            "FRIEND_REQUEST_ACCEPTED",
            "FRIEND_REQUEST_REJECTED",
            "FRIEND_REQUEST_CANCELED",
            "BLOCK_FRIEND",
            "UNBLOCK_FRIEND",
            "UNFRIEND",
            name="notification_type",
        ),
        existing_nullable=False,
    )
    op.drop_column("notifications", "receiver_id")
    # ### end Alembic commands ###
