"""Added notification request id

Revision ID: dcc32d86f9a3
Revises: d0f1ea7d2b3b
Create Date: 2024-09-07 12:33:06.279257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc32d86f9a3'
down_revision: Union[str, None] = 'd0f1ea7d2b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('request_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'users', ['request_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'request_id')
    # ### end Alembic commands ###
